language: node_js
node_js:
- 6.9.2
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: frodare@gmail.com
  api_key:
    secure: rbkA5iwM0qYdSRfHlBdF9/4CR/nCvnXZH7dat4/Fmz4w2B/kImVwovbJ7t3KP9QUdD2sassj3N4/uHIe20uvEDzuLeKtbXyjLzUMPexXV5DCoVYMwu1cbYv3ScDNBQJHGad+lCvRXLaJw3jGWmm7wjG+0usH4ziMEyTkfH55lyjoLKMGwAfCv05Ji8P1niLF9SGcw0+ofr4IQAoBA/7LVaxAdWFZ0n6lj5EhgUer0ZHU1Eb3W9Tk0Kzm12YUttx2nVJ64nsD2oGupHjOQqHSB2d0dWZ2wjLv+eSsQxctXZCmkt9bbe7gytudSYTzGMStiwmSfBIl59oLyHDQ+hS/k6PU3yiyXMhzQGlhiJr663j4vA7Kbyx1zMpVYNN8VzKKVOiM1Q/Z9XzpF914f9PHR4pHlke1MHsdU7H91k8faBlAyg5cq/5ffsnZV4Rpt+rOwHzwNDEhmsGz8XUrkLGMnb/MOgNmN+6nOr0ljF+07bqYNQ+xPqiaZ/1hH+U9Zuk0WPt5v0Syj6UT/FLpDkagofhjq8E+BumL3Y8bofm02JaZ9boVv3pm3NdfbY+Lgz/liOQS28FGGNixnvULhXHvikWarsvcMaN10QWJJi/wezkbwRPb5Y5fu8WIMbp7pAJZ/u6zXKuX2Zqd1j20MDAqAx0LBVK7HVFamXWIyOAW7Po=
  on:
    tags: true
    repo: autodatadirect/add-style
    branch: master
after_deploy: 
